name = "LibSerialPort"
uuid = "d9b8e1ca-a0b8-11e8-0e65-893722676106"
authors = ["Rehmi Post <rehmi.post@gmail.com>"]
version = "0.4.0"

[deps]
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
libserialport_jll = "220460dc-b50e-5ed0-8176-09b0fd261e90"

[compat]
julia = "1.3"
libserialport_jll = "0.1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
